# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('millicar', ['core', 'propagation', 'spectrum', 'newradio'])
    module.source = [
        'model/newradio-vehicular.cc',
        'model/newradio-vehicular-propagation-loss-model.cc',
        'model/newradio-vehicular-spectrum-propagation-loss-model.cc',
        'model/newradio-sidelink-spectrum-phy.cc',
        'model/newradio-sidelink-spectrum-signal-parameters.cc',
        'model/newradio-sidelink-phy.cc',
        'model/newradio-sidelink-mac.cc',
        'model/newradio-vehicular-net-device.cc',
        'model/newradio-vehicular-antenna-array-model.cc',
        'helper/newradio-vehicular-helper.cc',
        'helper/newradio-vehicular-traces-helper.cc'
        ]

    module_test = bld.create_ns3_module_test_library('millicar')
    module_test.source = [
        'test/newradio-vehicular-sidelink-spectrum-phy-test.cc',
        'test/newradio-sidelink-phy-test-suite.cc',
        'test/newradio-vehicular-rate-test.cc',
        'test/newradio-vehicular-interference-test.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'millicar'
    headers.source = [
        'model/newradio-vehicular.h',
        'model/newradio-vehicular-propagation-loss-model.h',
        'model/newradio-vehicular-spectrum-propagation-loss-model.h',
        'model/newradio-sidelink-spectrum-phy.h',
        'model/newradio-sidelink-spectrum-signal-parameters.h',
        'model/newradio-sidelink-phy.h',
        'model/newradio-sidelink-mac.h',
        'model/newradio-sidelink-sap.h',
        'model/newradio-vehicular-net-device.h',
        'model/newradio-vehicular-antenna-array-model.h',
        'helper/newradio-vehicular-helper.h',
        'helper/newradio-vehicular-traces-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
